# Generated by Django 5.0 on 2024-07-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("message1", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messagemodel",
            name="key_uuid",
        ),
        migrations.DeleteModel(
            name="DataSystemModel",
        ),
    ]
